# Generated by Django 5.0.7 on 2026-07-19 00:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportingPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_type', models.CharField(choices=[('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('ANNUAL', 'Annual')], db_index=True, max_length=20)),
                ('label', models.CharField(help_text="e.g., 'Week 26, 22-28 June 2026'", max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reporting_year', models.IntegerField()),
                ('week_number', models.IntegerField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('quarter', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open for Entry'), ('CLOSED', 'Closed'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('LOCKED', 'Locked'), ('REOPENED', 'Reopened')], db_index=True, default='DRAFT', max_length=20)),
                ('submission_deadline', models.DateTimeField(blank=True, null=True)),
                ('locked_date', models.DateTimeField(blank=True, null=True)),
                ('reopened_date', models.DateTimeField(blank=True, null=True)),
                ('reopen_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_periods', to=settings.AUTH_USER_MODEL)),
                ('reopened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reopened_periods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reporting_periods',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentPeriodScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('average_achievement', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('composite_score', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('kpi_count', models.IntegerField(default=0)),
                ('submitted_count', models.IntegerField(default=0)),
                ('on_track_count', models.IntegerField(default=0)),
                ('at_risk_count', models.IntegerField(default=0)),
                ('off_track_count', models.IntegerField(default=0)),
                ('no_data_count', models.IntegerField(default=0)),
                ('rag_status', models.CharField(blank=True, max_length=20)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_scores', to='organisation.department')),
                ('reporting_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_scores', to='periods.reportingperiod')),
            ],
            options={
                'db_table': 'department_period_scores',
            },
        ),
        migrations.AddIndex(
            model_name='reportingperiod',
            index=models.Index(fields=['period_type', 'reporting_year'], name='reporting_p_period__f9ee4c_idx'),
        ),
        migrations.AddIndex(
            model_name='reportingperiod',
            index=models.Index(fields=['status'], name='reporting_p_status_fa9d37_idx'),
        ),
        migrations.AddConstraint(
            model_name='reportingperiod',
            constraint=models.UniqueConstraint(condition=models.Q(('period_type', 'WEEKLY')), fields=('period_type', 'reporting_year', 'week_number'), name='unique_weekly_period'),
        ),
        migrations.AddConstraint(
            model_name='reportingperiod',
            constraint=models.UniqueConstraint(condition=models.Q(('period_type', 'MONTHLY')), fields=('period_type', 'reporting_year', 'month'), name='unique_monthly_period'),
        ),
        migrations.AddConstraint(
            model_name='reportingperiod',
            constraint=models.UniqueConstraint(condition=models.Q(('period_type', 'QUARTERLY')), fields=('period_type', 'reporting_year', 'quarter'), name='unique_quarterly_period'),
        ),
        migrations.AlterUniqueTogether(
            name='departmentperiodscore',
            unique_together={('department', 'reporting_period')},
        ),
    ]
