# Generated by Django 5.0.7 on 2026-07-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportingperiod',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open for Entry'), ('CLOSED', 'Closed'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('LOCKED', 'Locked'), ('REOPENED', 'Reopened')], db_index=True, default='OPEN', max_length=20),
        ),
    ]
