# Generated by Django 5.0.7 on 2026-07-23 12:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('periods', '0001_initial'),
        ('results', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('KPI_SUBMITTED', 'KPI Result Submitted'), ('KPI_APPROVED', 'KPI Result Approved'), ('KPI_RETURNED', 'KPI Result Returned'), ('KPI_AT_RISK', 'KPI At Risk'), ('KPI_OFF_TRACK', 'KPI Off Track'), ('PERIOD_OPENED', 'Period Opened'), ('PERIOD_CLOSING', 'Period Closing Soon'), ('PERIOD_CLOSED', 'Period Closed'), ('PERIOD_SUMMARY', 'Period Summary'), ('MEMBER_ADDED', 'Team Member Added'), ('ROLE_CHANGED', 'Role Changed'), ('CORRECTIVE_ACTION', 'Corrective Action Required'), ('COMMENT_ADDED', 'Comment Added')], max_length=30)),
                ('title', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, help_text='Frontend URL to navigate to', max_length=500)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_emailed', models.BooleanField(default=False)),
                ('kpi_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='results.kpiresult')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='periods.reportingperiod')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_a4dd5c_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_19df93_idx')],
            },
        ),
    ]
