# apps/kpis/management/commands/seed_presets.py
# Run: python manage.py seed_presets            (seeds ALL organisations)
#      python manage.py seed_presets --org <id> (seeds one)
# Idempotent: get_or_create means re-running won't duplicate.
from django.core.management.base import BaseCommand
from decimal import Decimal


STARTER = {
    "Sales": [
        ("Monthly Revenue", "Total closed revenue in the period", 100000, "$", "HIGHER_BETTER", "MONTHLY"),
        ("Conversion Rate", "Leads converted to customers", 25, "%", "HIGHER_BETTER", "MONTHLY"),
        ("New Deals Closed", "Count of deals won", 20, "count", "HIGHER_BETTER", "MONTHLY"),
        ("Pipeline Value", "Value of open opportunities", 500000, "$", "HIGHER_BETTER", "MONTHLY"),
    ],
    "Customer Support": [
        ("First Response Time", "Average time to first reply", 2, "hrs", "LOWER_BETTER", "WEEKLY"),
        ("CSAT Score", "Customer satisfaction rating", 90, "%", "HIGHER_BETTER", "MONTHLY"),
        ("Ticket Resolution Rate", "Tickets resolved vs opened", 95, "%", "HIGHER_BETTER", "WEEKLY"),
        ("Average Handle Time", "Mean time to resolve a ticket", 24, "hrs", "LOWER_BETTER", "WEEKLY"),
    ],
    "Operations": [
        ("On-Time Delivery", "Deliveries met on schedule", 98, "%", "HIGHER_BETTER", "MONTHLY"),
        ("Process Uptime", "System/process availability", 99, "%", "HIGHER_BETTER", "MONTHLY"),
        ("Defect Rate", "Errors per batch/output", 2, "%", "LOWER_BETTER", "MONTHLY"),
        ("Capacity Utilisation", "Resource usage vs available", 85, "%", "HIGHER_BETTER", "MONTHLY"),
    ],
    "Finance": [
        ("Budget Variance", "Actual vs budgeted spend", 5, "%", "LOWER_BETTER", "MONTHLY"),
        ("Gross Margin", "Revenue minus COGS", 40, "%", "HIGHER_BETTER", "QUARTERLY"),
        ("Days Sales Outstanding", "Average collection period", 30, "days", "LOWER_BETTER", "MONTHLY"),
        ("Operating Cash Flow", "Cash generated by operations", 200000, "$", "HIGHER_BETTER", "MONTHLY"),
    ],
    "HR": [
        ("Employee Retention", "Staff retained over period", 90, "%", "HIGHER_BETTER", "QUARTERLY"),
        ("Time to Hire", "Days from opening to offer", 30, "days", "LOWER_BETTER", "MONTHLY"),
        ("Training Completion", "Staff completing required training", 95, "%", "HIGHER_BETTER", "QUARTERLY"),
        ("Absenteeism Rate", "Unplanned absence rate", 3, "%", "LOWER_BETTER", "MONTHLY"),
    ],
    "General": [
        ("Goal Completion", "Objectives met in the period", 90, "%", "HIGHER_BETTER", "MONTHLY"),
        ("Quality Score", "Overall quality rating", 90, "%", "HIGHER_BETTER", "MONTHLY"),
        ("Cost Efficiency", "Output per unit cost", 85, "%", "HIGHER_BETTER", "MONTHLY"),
    ],
}


class Command(BaseCommand):
    help = "Seed starter KPI preset categories and presets for organisations."

    def add_arguments(self, parser):
        parser.add_argument("--org", type=str, default=None, help="Organisation id (default: all)")

    def handle(self, *args, **opts):
        from apps.organisation.models import Organisation
        from apps.kpis.models import KPIPresetCategory, KPIPreset

        orgs = Organisation.objects.all()
        if opts["org"]:
            orgs = orgs.filter(id=opts["org"])

        total = 0
        for org in orgs:
            for order, (cat_name, presets) in enumerate(STARTER.items()):
                cat, _ = KPIPresetCategory.objects.get_or_create(
                    organisation=org, name=cat_name,
                    defaults={"display_order": order},
                )
                for name, desc, target, unit, direction, freq in presets:
                    _, created = KPIPreset.objects.get_or_create(
                        organisation=org, category=cat, name=name,
                        defaults={
                            "description": desc,
                            "target_value": Decimal(str(target)),
                            "unit": unit,
                            "calculation_direction": direction,
                            "reporting_frequency": freq,
                            "warning_threshold": Decimal("0.85"),
                        },
                    )
                    total += 1 if created else 0
            self.stdout.write(self.style.SUCCESS(f"Seeded presets for {org.name}"))
        self.stdout.write(self.style.SUCCESS(f"Done. {total} new presets created."))