# Generated by Django 5.0.7 on 2026-07-18 23:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('calculation_direction', models.CharField(choices=[('HIGHER_IS_BETTER', 'Higher is Better'), ('LOWER_IS_BETTER', 'Lower is Better'), ('EXACT_TARGET', 'Exact Target'), ('RANGE', 'Range'), ('BOOLEAN', 'Boolean (Yes/No)'), ('MANUAL_SCORE', 'Manual Score')], default='HIGHER_IS_BETTER', max_length=20)),
                ('reporting_frequency', models.CharField(choices=[('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('ANNUAL', 'Annual')], default='MONTHLY', max_length=20)),
                ('unit_type', models.CharField(choices=[('PERCENTAGE', 'Percentage (%)'), ('NUMBER', 'Number / Count'), ('CURRENCY', 'Currency'), ('HOURS', 'Hours'), ('DAYS', 'Days'), ('SCORE', 'Score'), ('RATIO', 'Ratio'), ('BOOLEAN', 'Yes / No'), ('CUSTOM', 'Custom Unit')], default='PERCENTAGE', max_length=20)),
                ('custom_unit', models.CharField(blank=True, max_length=50)),
                ('target_value', models.DecimalField(decimal_places=4, help_text='Target value for the KPI', max_digits=15)),
                ('min_acceptable', models.DecimalField(blank=True, decimal_places=4, help_text='Minimum acceptable value (for RANGE type)', max_digits=15, null=True)),
                ('max_acceptable', models.DecimalField(blank=True, decimal_places=4, help_text='Maximum acceptable value (for RANGE type)', max_digits=15, null=True)),
                ('warning_threshold', models.DecimalField(decimal_places=4, default=0.85, help_text='Warning threshold as decimal (e.g., 0.85 = 85%)', max_digits=5)),
                ('critical_threshold', models.DecimalField(decimal_places=4, default=0.75, help_text='Critical threshold as decimal', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, help_text='KPI weight for weighted scoring (1.00 = standard)', max_digits=5)),
                ('decimal_precision', models.IntegerField(default=1)),
                ('allow_exceed_target', models.BooleanField(default=False, help_text='Allow achievement above 100%')),
                ('cap_achievement', models.BooleanField(default=True, help_text='Cap achievement at 100%')),
                ('zero_is_valid', models.BooleanField(default=True, help_text='Is zero a valid actual result?')),
                ('is_cumulative', models.BooleanField(default=False, help_text='Does this KPI accumulate over periods?')),
                ('data_source', models.TextField(blank=True, help_text='Where the data comes from')),
                ('evidence_required', models.BooleanField(default=False)),
                ('evidence_description', models.TextField(blank=True)),
                ('requires_approval', models.BooleanField(default=False)),
                ('contributes_to_average', models.BooleanField(default=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kpis', to='organisation.department')),
                ('department_owner', models.ForeignKey(blank=True, help_text='Department-level owner', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_kpis', to=settings.AUTH_USER_MODEL)),
                ('responsible_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_kpis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KPI',
                'verbose_name_plural': 'KPIs',
                'db_table': 'kpis',
                'ordering': ['department__display_order', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='KPIThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('warning_threshold', models.DecimalField(decimal_places=4, max_digits=5)),
                ('critical_threshold', models.DecimalField(decimal_places=4, max_digits=5)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thresholds', to='kpis.kpi')),
            ],
            options={
                'db_table': 'kpi_thresholds',
                'ordering': ['-start_date'],
            },
        ),
    ]
