# Generated by Django 5.0.7 on 2026-07-27 13:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KPIAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_made', to=settings.AUTH_USER_MODEL)),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='kpis.kpi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'kpi_assignments',
                'indexes': [models.Index(fields=['kpi', 'is_active'], name='kpi_assignm_kpi_id_9bba1d_idx'), models.Index(fields=['user', 'is_active'], name='kpi_assignm_user_id_777722_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='kpiassignment',
            constraint=models.UniqueConstraint(fields=('kpi', 'user'), name='unique_kpi_user_assignment'),
        ),
    ]
