# Generated by Django 5.0.7 on 2026-08-04 15:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_avatar'),
        ('kpis', '0002_kpiassignment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPIPresetCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('icon', models.CharField(blank=True, help_text='lucide icon name, optional', max_length=40)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_preset_categories', to='accounts.organisation')),
            ],
            options={
                'db_table': 'kpi_preset_categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='KPIPreset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('target_value', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('unit', models.CharField(blank=True, help_text='e.g. %, hrs, count, $', max_length=40)),
                ('calculation_direction', models.CharField(default='HIGHER_BETTER', help_text='HIGHER_BETTER / LOWER_BETTER / etc — match your KPI choices', max_length=20)),
                ('reporting_frequency', models.CharField(default='MONTHLY', help_text='WEEKLY / MONTHLY / QUARTERLY / ANNUAL', max_length=20)),
                ('warning_threshold', models.DecimalField(decimal_places=4, default=0.85, max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_presets', to='accounts.organisation')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presets', to='kpis.kpipresetcategory')),
            ],
            options={
                'db_table': 'kpi_presets',
                'ordering': ['category__display_order', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='kpipresetcategory',
            constraint=models.UniqueConstraint(fields=('organisation', 'name'), name='unique_org_preset_category_name'),
        ),
        migrations.AddIndex(
            model_name='kpipreset',
            index=models.Index(fields=['organisation', 'is_active'], name='kpi_presets_organis_a1f711_idx'),
        ),
        migrations.AddIndex(
            model_name='kpipreset',
            index=models.Index(fields=['category'], name='kpi_presets_categor_6306c1_idx'),
        ),
    ]
