# Generated by Django 5.0.7 on 2026-07-18 23:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdepartment',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='organisation.department'),
        ),
        migrations.AddField(
            model_name='userdepartment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userdepartment',
            unique_together={('user', 'department')},
        ),
    ]
