# Generated by Django 5.0.7 on 2026-07-20 15:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='custom_title',
            field=models.CharField(blank=True, help_text="Custom job title if 'Other' selected", max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Team leader or admin who manages this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, choices=[('TECHNICAL_SUPPORT', 'Technical Support'), ('INTERN', 'Intern'), ('ANALYST', 'Analyst'), ('ENGINEER', 'Engineer'), ('MANAGER', 'Manager'), ('DIRECTOR', 'Director'), ('COORDINATOR', 'Coordinator'), ('SPECIALIST', 'Specialist'), ('CONSULTANT', 'Consultant'), ('OTHER', 'Other')], default='OTHER', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('TEAM_LEADER', 'Team Leader'), ('MEMBER', 'Member')], default='MEMBER', max_length=20),
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_organisations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'organisations',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='accounts.organisation'),
        ),
        migrations.DeleteModel(
            name='UserDepartment',
        ),
    ]
