# Generated by Django 5.0.7 on 2026-07-20 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_custom_title_user_manager_user_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_organisations', to=settings.AUTH_USER_MODEL),
        ),
    ]
