# Generated by Django 5.0.7 on 2026-09-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_period_reminders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]
