# Generated by Django 5.0.7 on 2026-07-18 23:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(help_text='Short code e.g. OPS, BD', max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('colour', models.CharField(default='#3B82F6', help_text='Hex colour for charts', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('weekly_reporting', models.BooleanField(default=True)),
                ('monthly_reporting', models.BooleanField(default=True)),
                ('quarterly_reporting', models.BooleanField(default=True)),
                ('annual_reporting', models.BooleanField(default=True)),
                ('department_head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'departments',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
