# Generated by Django 5.0.7 on 2026-07-20 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_organisation_created_by'),
        ('organisation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='accounts.organisation'),
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(help_text='Short code e.g. OPS, BD', max_length=20),
        ),
        migrations.AlterField(
            model_name='department',
            name='colour',
            field=models.CharField(default='#3B82F6', max_length=7),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('organisation', 'code')},
        ),
        migrations.CreateModel(
            name='UserDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_department_head', models.BooleanField(default=False)),
                ('is_primary', models.BooleanField(default=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_links', to='organisation.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_departments',
                'unique_together': {('user', 'department')},
            },
        ),
    ]
