# Generated by Django 5.0.7 on 2026-07-28 07:45
# EDITED: chatroom.created_by and chatroom.is_private already exist in the DB
# (drift from an earlier state), so those two AddFields are wrapped in
# SeparateDatabaseAndState — Django records them in migration STATE but runs no
# SQL for them. Everything else (reply_to, the 3 new tables) runs normally.

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # --- genuinely new: create the column ---
        migrations.AddField(
            model_name='chatmessage',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='chat.chatmessage'),
        ),

        # --- already exist in DB: update state only, emit NO SQL ---
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='chatroom',
                    name='created_by',
                    field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_chat_rooms', to=settings.AUTH_USER_MODEL),
                ),
                migrations.AddField(
                    model_name='chatroom',
                    name='is_private',
                    field=models.BooleanField(default=False),
                ),
            ],
            database_operations=[],  # columns already present — do nothing in the DB
        ),

        # --- genuinely new tables ---
        migrations.CreateModel(
            name='RoomInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('allowed_emails', models.JSONField(blank=True, default=list)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_invites_created', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='chat.chatroom')),
            ],
            options={
                'db_table': 'chat_room_invites',
            },
        ),
        migrations.CreateModel(
            name='RoomRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='chat.chatroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_reads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_room_reads',
            },
        ),
        migrations.CreateModel(
            name='MessageReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emoji', models.CharField(max_length=32)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='chat.chatmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_message_reactions',
                'indexes': [models.Index(fields=['message', 'emoji'], name='chat_messag_message_723290_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='messagereaction',
            constraint=models.UniqueConstraint(fields=('message', 'user', 'emoji'), name='unique_message_user_emoji'),
        ),
        migrations.AddConstraint(
            model_name='roomread',
            constraint=models.UniqueConstraint(fields=('room', 'user'), name='unique_room_user_read'),
        ),
    ]