# Generated by Django 5.0.7 on 2026-07-19 01:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisation', '0001_initial'),
        ('results', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectiveAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('problem_statement', models.TextField()),
                ('root_cause', models.TextField(blank=True)),
                ('corrective_action', models.TextField()),
                ('preventive_action', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('AWAITING_EVIDENCE', 'Awaiting Evidence'), ('AWAITING_REVIEW', 'Awaiting Review'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled'), ('OVERDUE', 'Overdue')], db_index=True, default='OPEN', max_length=25)),
                ('date_raised', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completion_percentage', models.IntegerField(default=0)),
                ('closure_date', models.DateTimeField(blank=True, null=True)),
                ('closure_notes', models.TextField(blank=True)),
                ('effectiveness_review', models.TextField(blank=True)),
                ('action_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_actions', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corrective_actions', to='organisation.department')),
                ('kpi_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrective_actions', to='results.kpiresult')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'corrective_actions',
                'ordering': ['-date_raised'],
                'indexes': [models.Index(fields=['status'], name='corrective__status_b54c4e_idx'), models.Index(fields=['due_date'], name='corrective__due_dat_5b2445_idx'), models.Index(fields=['department'], name='corrective__departm_705805_idx')],
            },
        ),
    ]
